### ISSUE TITLE
Form app problem

### ISSUE THREAD

**Issue by imjustprism** [Mecanik/Anti-DebugNET#5]
My form not load if `AntiDebug.DebugProtect3.HideOSThreads();` or `AntiDump.DumpProtect1.AntiDump();` in the program.cs, i mean the program running in the background, but the form not visible and the proection not work like i can dump with megadumper

**Comment by Mecanik** [comment]
Really sorry for the late reply, did not see the notification. 

1. The reason why your form does not show is because you are probably calling the function in the wrong place and it hides your mai UI thread.

2. Anti-Dump function erases headers at runtime and might not be compatible with all builds. Without seeing your code it's impossible to guess.
